version: '2.0'
services:
  registry:
    image: registry:2.6.2
    container_name: docker-registry
    restart: always
    ports:
    - 7000:5000
    volumes:
      - ./registry-data:/var/lib/registry
    

  ui:
    image: joxit/docker-registry-ui:static
    container_name: docker-registry-ui
    restart: always
    ports:
      - 4000:80
    environment:
      - REGISTRY_TITLE=private-docker-regitry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    

