apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: exam
type: Opaque
data:
  # username = admin base64 encoded
  db.username: J2FzbWFlJyANCg==
  # password = asmae base64 encoded
  db.password: J2FkbWluJyANCg==
