apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-volume
  namespace: exam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mongo